//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintumProjektverwaltung.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adressen
    {
        public int AdressID { get; set; }
        public string Name { get; set; }
        public string Strasse { get; set; }
        public string PLZ { get; set; }
        public string Ort { get; set; }
        public string Land { get; set; }
        public string ZuHaendenVon { get; set; }
        public string Firmenname { get; set; }
        public string Email1Adresse { get; set; }
        public string Email2Adresse { get; set; }
        public string Telefon1 { get; set; }
        public string PLZundORT { get; set; }
        public string Matchcode { get; set; }
        public string JobTitle { get; set; }
        public string FileAs { get; set; }
        public string businessHomePage { get; set; }
        public string Categories { get; set; }
        public string ID { get; set; }
        public string TelefonMobile { get; set; }
        public string Vorname { get; set; }
        public string Nachname { get; set; }
        public string RechnungName { get; set; }
        public string RechnungStrasse { get; set; }
        public string RechnungPLZ { get; set; }
        public string RechnungOrt { get; set; }
        public string RechnungLand { get; set; }
    }
}
