//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintumProjektverwaltung.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bestellungen
    {
        public int Bestellung_ID { get; set; }
        public string BestellungIDText { get; set; }
        public Nullable<int> Projektnummer { get; set; }
        public string Adresse { get; set; }
        public string Speicherort { get; set; }
        public string Vorlage { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public string ErstelltVon { get; set; }
        public string GeaendertVon { get; set; }
        public Nullable<System.DateTime> geaendert { get; set; }
        public string PDFpfad { get; set; }
        public Nullable<bool> istAbgeschickt { get; set; }
        public string AdressID { get; set; }
        public string EmailAdresse { get; set; }
        public Nullable<bool> AB { get; set; }
        public Nullable<bool> WA { get; set; }
    }
}
