//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintumProjektverwaltung.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BestellungPositionen_View
    {
        public Nullable<int> Projektnummer { get; set; }
        public string Projektname { get; set; }
        public string BestellnungIDTest { get; set; }
        public Nullable<int> Pos { get; set; }
        public string Artikelbezeichnung { get; set; }
        public Nullable<int> Stueck { get; set; }
        public string Besteller { get; set; }
        public Nullable<System.DateTime> Bestelldatum { get; set; }
        public Nullable<System.DateTime> Liefertermin { get; set; }
        public Nullable<System.DateTime> AB_datum { get; set; }
        public string ABestaetiger { get; set; }
        public Nullable<System.DateTime> WE_datum { get; set; }
        public string WEingaenger { get; set; }
        public Nullable<double> Einzelpreis { get; set; }
        public Nullable<double> Gesammtpreis { get; set; }
        public string Lagerort { get; set; }
    }
}
