//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintumProjektverwaltung.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Einheit
    {
        public int EinheitID { get; set; }
        public string EinheitNummer { get; set; }
        public string Beschreibung { get; set; }
        public string BeschreibungEnglish { get; set; }
        public Nullable<decimal> Preis { get; set; }
        public Nullable<int> Rabatt { get; set; }
        public Nullable<int> Zahlungsstaffel1 { get; set; }
        public Nullable<int> Zahlungsstaffel2 { get; set; }
        public Nullable<int> Zahlungsstaffel3 { get; set; }
        public string Zahlungsbedingung { get; set; }
        public string ZahlungsbedingungEnglish { get; set; }
        public string Garantie { get; set; }
        public string GarantieEnglish { get; set; }
        public string TechnischAbnahme { get; set; }
        public string TechnischAbnahmeEnglish { get; set; }
        public string Eigentumsvorbehalt { get; set; }
        public string EigentumsvorbehaltEnglish { get; set; }
        public string Gerichtsstand { get; set; }
        public string GerichtsstandEnglish { get; set; }
        public string AGB { get; set; }
        public string AGBEnglish { get; set; }
        public string Wichtig { get; set; }
        public string WichtigEnglish { get; set; }
        public Nullable<int> Lieferzeit { get; set; }
        public string Lieferbedingunen { get; set; }
        public string LieferbedingungenEnglish { get; set; }
        public string Montagebedingungen { get; set; }
        public string MontagebedingungenEnglish { get; set; }
        public string Preisbindung { get; set; }
        public string PreisbindungEnglish { get; set; }
        public string Bezeichnung { get; set; }
        public string BezeichnungEnglich { get; set; }
    }
}
