//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintumProjektverwaltung.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LieferungPositionen
    {
        public int PositionenID { get; set; }
        public Nullable<int> PositionNr { get; set; }
        public Nullable<int> ArtikeID { get; set; }
        public string Artikelnummer { get; set; }
        public string Beschreibung { get; set; }
        public string BeschreibungEnglish { get; set; }
        public Nullable<decimal> Preis { get; set; }
        public Nullable<double> Anzahl { get; set; }
        public string Mengeneinheit { get; set; }
        public Nullable<int> EinheitID { get; set; }
        public string Einheit { get; set; }
        public Nullable<int> AuftragID { get; set; }
        public string AuftragNummer { get; set; }
        public Nullable<System.DateTime> HinzugefuegtAm { get; set; }
        public string HinzugefuegtVon { get; set; }
        public string HinzugefuegtGrund { get; set; }
        public Nullable<System.DateTime> GeaenderAm { get; set; }
        public string GeaendertVon { get; set; }
        public string GeaendertGrund { get; set; }
        public Nullable<System.DateTime> GeloeschtAm { get; set; }
        public string GeloeschtVon { get; set; }
        public string GeloeschtGrund { get; set; }
    }
}
