//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintumProjektverwaltung.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lieferung
    {
        public int AuftagID { get; set; }
        public string AuftragNummer { get; set; }
        public string Bezeichnung { get; set; }
        public string AdressLieferName { get; set; }
        public string AdressLieferStrasse { get; set; }
        public string AdressLieferPLZ { get; set; }
        public string AdressLieferOrt { get; set; }
        public string AdressLieferLand { get; set; }
        public string AdressRechnungName { get; set; }
        public string AdressRechnungStrasse { get; set; }
        public string AdressRechnungPLZ { get; set; }
        public string AdressRechnungOrt { get; set; }
        public string AdressRechnungLand { get; set; }
        public Nullable<int> RechnungID1 { get; set; }
        public string RechnungNummer1 { get; set; }
        public Nullable<int> RechnungID2 { get; set; }
        public string RechnungNummer2 { get; set; }
        public Nullable<int> RechnungID3 { get; set; }
        public string RechnungNummer3 { get; set; }
        public Nullable<int> RechnungID4 { get; set; }
        public string RechnungNummer4 { get; set; }
        public Nullable<int> LieferscheinID { get; set; }
        public string LieferscheinNummer { get; set; }
        public Nullable<int> EinheitID { get; set; }
        public string EinheitNummer { get; set; }
        public Nullable<int> Projektnummer { get; set; }
        public string Projektname { get; set; }
        public Nullable<int> aktiv { get; set; }
    }
}
