//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintumProjektverwaltung.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LieferungLieferschein
    {
        public int LieferscheinID { get; set; }
        public string LieferscheinNummer { get; set; }
        public Nullable<int> AuftagID { get; set; }
        public string AuftragNummer { get; set; }
        public string LieferscheinPfadPDF { get; set; }
        public Nullable<System.DateTime> Lieferdatum { get; set; }
        public string Lieferscheintext1 { get; set; }
        public string Lieferscheintext2 { get; set; }
        public string Lieferscheintext3 { get; set; }
        public Nullable<System.DateTime> LieferscheinErstelltAm { get; set; }
        public string LieferscheinErstelltVon { get; set; }
        public string Lieferscheintext4 { get; set; }
    }
}
