//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintumProjektverwaltung.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LieferungRechnungen
    {
        public int RechnungID { get; set; }
        public string RechnungNummer { get; set; }
        public Nullable<int> AuftragID { get; set; }
        public string AuftragNummer { get; set; }
        public Nullable<decimal> RechnungBetrag { get; set; }
        public Nullable<System.DateTime> RechnungErstelltAm { get; set; }
        public string RechnungErstelltVon { get; set; }
        public string RechnungPfadPDF { get; set; }
        public Nullable<System.DateTime> RechnungBezahltAm { get; set; }
        public Nullable<decimal> RechnungBetragBezahlt { get; set; }
        public Nullable<System.DateTime> RechnungMahnung1Am { get; set; }
        public string RechnungMahnung1PfadPDF { get; set; }
        public Nullable<System.DateTime> RechnungMahnung2Am { get; set; }
        public string RechnungMahnung2PfadPDF { get; set; }
    }
}
