//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintumProjektverwaltung.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mails
    {
        public int Mail_ID { get; set; }
        public Nullable<int> Projektnummer { get; set; }
        public string von { get; set; }
        public string an { get; set; }
        public string Betreff { get; set; }
        public string Body { get; set; }
        public string AnhangJSON { get; set; }
        public string Speicherort { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public string Schlagworte { get; set; }
    }
}
