//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintumProjektverwaltung.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordner
    {
        public int Ordner_ID { get; set; }
        public Nullable<int> Projektnummer { get; set; }
        public string Name { get; set; }
        public string Pfad { get; set; }
        public string Unterordner { get; set; }
        public string Root { get; set; }
        public Nullable<bool> hatDateien { get; set; }
    }
}
