//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintumProjektverwaltung.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriProLieferscheinRechnung
    {
        public int PriProLieferscheinRechnungID { get; set; }
        public string LieferscheinNr { get; set; }
        public string LieferscheinBeschreibung { get; set; }
        public Nullable<System.DateTime> LieferscheinDatum { get; set; }
        public string LieferscheinErsteller { get; set; }
        public string LS_Firmenname { get; set; }
        public string LS_Name { get; set; }
        public string LS_Strasse { get; set; }
        public string LS_PLZ { get; set; }
        public string LS_Stadt { get; set; }
        public string LS_Land { get; set; }
        public string LieferscheinPfad { get; set; }
        public string RechnungsNr { get; set; }
        public Nullable<double> RechnungBetrag { get; set; }
        public string RechnungBerechnungsgrund { get; set; }
        public Nullable<System.DateTime> RechnungDatum { get; set; }
        public string RechnungErsteller { get; set; }
        public string RE_Firmenname { get; set; }
        public string RE_Name { get; set; }
        public string RE_Strasse { get; set; }
        public string RE_PLZ { get; set; }
        public string RE_Stadt { get; set; }
        public string RE_Land { get; set; }
        public string RechnungPfad { get; set; }
        public Nullable<int> Projektnummer { get; set; }
        public string Projektname { get; set; }
    }
}
