//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintumProjektverwaltung.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriProRechnung
    {
        public int PriProRechnungID { get; set; }
        public string RechnungNr { get; set; }
        public string RechnungBeschreibung { get; set; }
        public string RechnungTyp { get; set; }
        public Nullable<System.DateTime> RechnungDatum { get; set; }
        public string RechnungErsteller { get; set; }
        public string RE_Firmenname { get; set; }
        public string RE_Name { get; set; }
        public string RE_Strasse { get; set; }
        public string RE_PLZ { get; set; }
        public string RE_Stadt { get; set; }
        public string RE_Land { get; set; }
        public string RechnungPfad { get; set; }
        public Nullable<int> Projektnummer { get; set; }
        public string Projektname { get; set; }
        public string LieferscheinNr { get; set; }
        public Nullable<double> Rechnungsbetrag { get; set; }
        public Nullable<System.DateTime> Zahlungsdatum { get; set; }
        public Nullable<double> Zahlungsbetrag { get; set; }
    }
}
